# Use a Node.js base image
FROM node:22.11.0-alpine

# Set the working directory inside the container
WORKDIR /app

RUN npm install -g pnpm

# Copy package.json and yarn.lock (or package-lock.json) to leverage Docker's cache
COPY package.json ./

# Install dependencies
RUN pnpm install --no-frozen-lockfile

# Copy the rest of your application code
COPY . .

# Expose the port Next.js runs on (default is 3000)
EXPOSE 3000

# Command to run the Next.js development server
CMD ["pnpm", "dev"]